# Generated by Django 2.2.4 on 2019-08-30 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_email_accounts', '0002_django18_compat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremail',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='django_email_accounts.User'),
        ),
    ]
