#!/bin/sh

set -e 

case "$1" in
    configure)
	adduser --system --group --shell /bin/bash \
	        --gecos "Package Tracking System User" \
		--home /var/lib/package-tracking-system \
		pts >/dev/null
	if [ "$2" = "" ]; then
	    chown -R pts:pts /var/cache/package-tracking-system \
			     /var/lib/package-tracking-system \
			     /var/log/package-tracking-system
	fi
	# Create the secret key
	if [ ! -f /var/lib/package-tracking-system/key ]; then
	    pwgen -s -y 50 > /var/lib/package-tracking-system/key
	    chown pts:pts /var/lib/package-tracking-system/key
	    chmod 640 /var/lib/package-tracking-system/key
	fi
    ;;
esac

#DEBHELPER#

exit 0
