# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_drop_priority_section_on_source_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcepackagerepositoryentry',
            name='component',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
