# Generated by Django 2.0.2 on 2018-03-23 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_sourcepackagerepositoryentry_component'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PackageExtractedInfo',
            new_name='PackageData',
        ),
    ]
