# Generated by Django 2.0.2 on 2018-03-23 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_packageextractedinfo_packagedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagedata',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='core.PackageName'),
        ),
    ]
