# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-29 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_packagedata_to_package_related_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=250, unique=True)),
                ('task_is_pending', models.BooleanField(default=False)),
                ('run_lock', models.DateTimeField(default=None, null=True)),
                ('last_attempted_run', models.DateTimeField(default=None, null=True)),
                ('last_completed_run', models.DateTimeField(default=None, null=True)),
                ('data', jsonfield.fields.JSONField(default=dict)),
                ('data_checksum', models.CharField(default=None, max_length=40, null=True)),
                ('version', models.IntegerField(default=0)),
            ],
        ),
    ]
