# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-20 21:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_taskdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RunningJob',
        ),
    ]
