# Generated by Django 2.2.4 on 2019-09-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_aliothdebiannet_list_archives'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binarypackage',
            name='version',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sourcepackage',
            name='version',
            field=models.CharField(max_length=200),
        ),
    ]
